
title: Sysmon Configuration Error
ruletype: Sigma
author: frack113
date: 2021/06/04
description: Detects when an adversary is trying to hide it's action from Sysmon logging
  based on error messages
detection:
  SELECTION_1:
    EventID: 255
  SELECTION_2:
    Channel: Microsoft-Windows-Sysmon/Operational
  SELECTION_3:
    Description:
    - '*Failed to open service configuration with error*'
    - '*Failed to connect to the driver to update configuration*'
  SELECTION_4:
    Description: '*Failed to open service configuration with error*'
  SELECTION_5:
    Description: '*Last error: The media is write protected.*'
  SELECTION_6:
    Description:
    - '*Failed to open service configuration with error 19*'
    - '*Failed to open service configuration with error 93*'
  condition: ((SELECTION_1 and SELECTION_2) and SELECTION_3 and  not ((SELECTION_4
    and SELECTION_5) or (SELECTION_6)))
falsepositives:
- Legitimate administrative action
id: 815cd91b-7dbc-4247-841a-d7dd1392b0a8
level: high
logsource:
  category: sysmon_error
  product: windows
modified: 2022/07/07
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
- https://talesfrominfosec.blogspot.com/2017/12/killing-sysmon-silently.html
status: experimental
tags:
- attack.defense_evasion
- attack.t1564
