title: An Application Is Uninstalled
ruletype: Sigma
author: frack113
date: 2022/01/28
description: An application has been removed. Check if it is critical
detection:
    SELECTION_1:
        Channel: Application
    SELECTION_2:
        Provider_Name: MsiInstaller
    SELECTION_3:
        EventID: 11724
    SELECTION_4:
        EventID: 1034
    condition: (SELECTION_1 and SELECTION_2 and (SELECTION_3 or SELECTION_4))
falsepositives:
- Unknown
id: 570ae5ec-33dc-427c-b815-db86228ad43e
level: low
logsource:
    product: windows
    service: application
status: experimental
tags:
- attack.impact
- attack.t1489

