title: Invoke-Obfuscation STDIN+ Launcher
ruletype: Sigma
author: Jonathan Cheong, oscd.community
date: 2020/10/15
description: Detects Obfuscated use of stdin to execute PowerShell
detection:
    SELECTION_1:
        Channel: Security
    SELECTION_2:
        EventID: 4697
    SELECTION_3:
        ServiceFileName: '*cmd*'
    SELECTION_4:
        ServiceFileName: '*powershell*'
    SELECTION_5:
        ServiceFileName:
        - '*${input}*'
        - '*noexit*'
    SELECTION_6:
        ServiceFileName:
        - '* /c *'
        - '* /r *'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5
        and SELECTION_6)
falsepositives:
- Unknown
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
level: high
logsource:
    product: windows
    service: security
modified: 2022/02/03
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
-   id: 72862bf2-0eb1-11eb-adc1-0242ac120002
    type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001

