title: Invoke-Obfuscation Via Use Clip
ruletype: Sigma
author: Nikita Nazarov, oscd.community
date: 2020/10/09
description: Detects Obfuscated Powershell via use Clip.exe in Scripts
detection:
    SELECTION_1:
        Channel: Security
    SELECTION_2:
        EventID: 4697
    SELECTION_3:
        ServiceFileName: '*(Clipboard|i*'
    condition: (SELECTION_1 and SELECTION_2 and SELECTION_3)
falsepositives:
- Unknown
id: 1a0a2ff1-611b-4dac-8216-8a7b47c618a6
level: high
logsource:
    product: windows
    service: security
modified: 2022/04/26
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
-   id: 63e3365d-4824-42d8-8b82-e56810fefa0c
    type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
yml_filename: win_invoke_obfuscation_via_use_clip_services_security.yml
yml_path: rules/windows/builtin/security
---

