
title: Invoke-Obfuscation COMPRESS OBFUSCATION
author: Timur Zinniatullin, oscd.community
date: 2020/10/18
description: Detects Obfuscated Powershell via COMPRESS OBFUSCATION
detection:
  SELECTION_1:
    Channel: Security
  SELECTION_2:
    EventID: 4697
  SELECTION_3:
    ServiceFileName: '*new-object*'
  SELECTION_4:
    ServiceFileName: '*text.encoding]::ascii*'
  SELECTION_5:
    ServiceFileName: '*readtoend*'
  SELECTION_6:
    ServiceFileName:
    - '*system.io.compression.deflatestream*'
    - '*system.io.streamreader*'
  condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5
    and SELECTION_6)
falsepositives:
- unknown
id: 7a922f1b-2635-4d6c-91ef-af228b198ad3
level: medium
logsource:
  product: windows
  service: security
modified: 2022/02/03
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 175997c5-803c-4b08-8bb0-70b099f47595
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
