author: Zach Mathis
date: 2022/03/23
modified: 2023/01/13

title: 'Reg Key Value Set (Sysmon Alert)'
description: |
    This Registry event type identifies Registry value modifications.
    The event records the value written for Registry values of type DWORD and QWORD.
details: 'Rule: %RuleName% ¦ EventType: %EventType% ¦ TgtObj: %TargetObject% ¦ %Details% ¦ Proc: %Image% ¦ PID: %ProcessId% ¦ PGUID: %ProcessGuid%'

id: 78431930-a5c6-46ae-b02c-fcdc2a7325c2
level: medium
status: stable
logsource:
    product: windows
    service: sysmon
    definition: 'Sysmon needs to be installed and configured.'
detection:
    selection_basic:
        Channel: Microsoft-Windows-Sysmon/Operational
        EventID: 13
    filter_no_alerts:
        - RuleName: ''
        - RuleName: '-'
    condition: selection_basic and not filter_no_alerts
falsepositives:
tags:
    - sysmon
references:
    - https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon
ruletype: Hayabusa

sample-evtx: |
    <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
        <System>
            <Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385F-C22A-43E0-BF4C-06F5698FFBD9}"/>
            <EventID>13</EventID>
            <Version>2</Version>
            <Level>4</Level>
            <Task>13</Task>
            <Opcode>0</Opcode>
            <Keywords>0x8000000000000000</Keywords>
            <TimeCreated SystemTime="2022-01-26T09:20:52.811383900Z"/>
            <EventRecordID>57280</EventRecordID>
            <Correlation/>
            <Execution ProcessID="1048" ThreadID="1684"/>
            <Channel>Microsoft-Windows-Sysmon/Operational</Channel>
            <Computer>fs03vuln.offsec.lan</Computer>
            <Security UserID="S-1-5-18"/>
        </System>
        <EventData>
            <Data Name="RuleName">technique_id=T1003,technique_name=Credential Dumping</Data>
            <Data Name="EventType">SetValue</Data>
            <Data Name="UtcTime">2022-01-26 09:20:52.811</Data>
            <Data Name="ProcessGuid">{A57649D1-1271-61F1-315A-8E1500000000}</Data>
            <Data Name="ProcessId">1524</Data>
            <Data Name="Image">C:\Windows\system32\reg.exe</Data>
            <Data Name="TargetObject">HKLM\System\CurrentControlSet\Control\SecurityProviders\WDigest\UseLogonCredential</Data>
            <Data Name="Details">DWORD (0x00000001)</Data>
        </EventData>
    </Event>