title: DeviceCredentialDeployment Execution
id: bf39ad4c-8a90-0e00-7076-2436ebb83b41
related:
    - id: b8b1b304-a60f-4999-9a6e-c547bde03ffd
      type: derived
status: test
description: Detects the execution of DeviceCredentialDeployment to hide a process from view
references:
    - https://github.com/LOLBAS-Project/LOLBAS/pull/147
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-19
tags:
    - attack.defense-evasion
    - attack.t1218
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    selection:
        NewProcessName|endswith: \DeviceCredentialDeployment.exe
    condition: process_creation and selection
falsepositives:
    - Unlikely
level: medium
ruletype: Sigma
