title: Rundll32 JS RunHTMLApplication Pattern
ruletype: Sigma
author: Florian Roth
date: 2022/01/14
description: Detects suspicious command line patterns used when rundll32 is used to
    run JavaScript code
detection:
    SELECTION_1:
        EventID: 4688
    SELECTION_2:
        Channel: Security
    SELECTION_3:
        CommandLine: '*rundll32*'
    SELECTION_4:
        CommandLine: '*javascript*'
    SELECTION_5:
        CommandLine: '*..\..\mshtml,RunHTMLApplication*'
    SELECTION_6:
        CommandLine: '*;document.write();GetObject("script*'
    condition: ((SELECTION_1 and SELECTION_2) and ((SELECTION_3 and SELECTION_4 and
        SELECTION_5) or SELECTION_6))
falsepositives:
- Unlikely
id: 9f06447a-a33a-4cbe-a94f-a3f43184a7a3
level: high
logsource:
    category: process_creation
    product: windows
references:
- http://hyp3rlinx.altervista.org/advisories/MICROSOFT_WINDOWS_DEFENDER_DETECTION_BYPASS.txt
status: experimental
tags:
- attack.defense_evasion

